### ISSUE TITLE
# Epic: New parameters in metadata.yml

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/models#57]
## Purpose
To improve user experience by providing better organization and filtering capabilities for models in the model hub.

## Current Parameters
```
version: 1 # Increment from v1 to indicate new schema
name: string  # Unique identifier for the model
default: string  # Default quantization/variant of the model
```

## New Parameters - Model Capabilities
```
context_length: integer  # Maximum context window size
modalities:  # Supported input/output types
  type: array
  enum: 
    - text
    - vision 
    - speech
    - multimodal

series: string  # Model architecture family (e.g., Llama, Mistral, Phi)
base_model: string  # Original base model name
license: string  # Model license type
release_date: date  # Initial release date of this version (mm/dd/yyyy)

categories:  # Primary use cases/strengths
  type: array
  enum:
    - general
    - coding
    - math
    - roleplay
    - analysis
    - creative
    - chat

supported_engines:  # Compatible inference engines
  type: array
  enum:
    - llama.cpp
    - onnx
    - tensorrt-llm
    - api

tool_support:  # Function calling/tool usage capabilities
  type: object
  properties:
    enabled: boolean
    supported_tools:
      type: array
      items: string  # e.g., "web_search", "code_interpreter"
```

## Example
```yaml
version: 1
name: amd-olmo
default: 1b-gguf-q4-km

# Capabilities
context_length: 8192
modalities: 
  - text

# Information
series: olmo
base_model: olmo-1b
license: apache-2.0
release_date: 10/30/2024

# Categories
categories:
  - general
  - coding

# Technical
supported_engines:
  - llama.cpp

tool_support:
  enabled: false
  supported_tools: []
```
